apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: atulbhatt123/netflix:latest  # Update with your image
        ports:
        - containerPort: 3000               # Change if different
