apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  type: NodePort
  selector:
    app: netflix
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080  # Optional: choose a specific port
